"""Database layer for JuruMatch.

Uses PostgreSQL when DATABASE_URL is set (Render), otherwise falls back to
SQLite for local development.
"""
import json
import os
import sqlite3
from datetime import datetime

DATABASE_URL = os.getenv("DATABASE_URL", "").strip()
USE_POSTGRES = bool(DATABASE_URL)
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DB_PATH = os.path.join(BASE_DIR, "sirekomjur.db")


def _postgres_url():
    # Some providers still expose the legacy postgres:// scheme.
    if DATABASE_URL.startswith("postgres://"):
        return "postgresql://" + DATABASE_URL[len("postgres://"):]
    return DATABASE_URL


def get_koneksi():
    if USE_POSTGRES:
        import psycopg
        from psycopg.rows import dict_row
        return psycopg.connect(_postgres_url(), row_factory=dict_row)

    konn = sqlite3.connect(DB_PATH)
    konn.row_factory = sqlite3.Row
    return konn


def _execute(konn, sql, params=()):
    """Execute SQL with the correct placeholder syntax for the backend."""
    if USE_POSTGRES:
        return konn.execute(sql, params)
    return konn.execute(sql.replace("%s", "?"), params)


def init_db():
    konn = get_koneksi()
    try:
        if USE_POSTGRES:
            _execute(konn, """
                CREATE TABLE IF NOT EXISTS users (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    nama TEXT NOT NULL,
                    email TEXT NOT NULL UNIQUE,
                    password_hash TEXT NOT NULL,
                    role TEXT NOT NULL DEFAULT 'user',
                    dibuat_pada TEXT NOT NULL
                )
            """)
            _execute(konn, """
                CREATE TABLE IF NOT EXISTS hasil_tes (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id INTEGER,
                    nama TEXT,
                    skor_r DOUBLE PRECISION,
                    skor_i DOUBLE PRECISION,
                    skor_a DOUBLE PRECISION,
                    skor_s DOUBLE PRECISION,
                    skor_e DOUBLE PRECISION,
                    skor_c DOUBLE PRECISION,
                    kode_holland TEXT,
                    rekomendasi_json TEXT,
                    dibuat_pada TEXT,
                    FOREIGN KEY(user_id) REFERENCES users(id)
                )
            """)
        else:
            _execute(konn, """
                CREATE TABLE IF NOT EXISTS users (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    nama TEXT NOT NULL,
                    email TEXT NOT NULL UNIQUE,
                    password_hash TEXT NOT NULL,
                    role TEXT NOT NULL DEFAULT 'user',
                    dibuat_pada TEXT NOT NULL
                )
            """)
            _execute(konn, """
                CREATE TABLE IF NOT EXISTS hasil_tes (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    user_id INTEGER,
                    nama TEXT,
                    skor_r REAL,
                    skor_i REAL,
                    skor_a REAL,
                    skor_s REAL,
                    skor_e REAL,
                    skor_c REAL,
                    kode_holland TEXT,
                    rekomendasi_json TEXT,
                    dibuat_pada TEXT,
                    FOREIGN KEY(user_id) REFERENCES users(id)
                )
            """)
            cols = [r["name"] for r in _execute(konn, "PRAGMA table_info(hasil_tes)").fetchall()]
            if "user_id" not in cols:
                _execute(konn, "ALTER TABLE hasil_tes ADD COLUMN user_id INTEGER")

        # Create/update the initial admin account from environment variables.
        # On Render, set ADMIN_EMAIL and ADMIN_PASSWORD in the service settings.
        admin_email = os.getenv("ADMIN_EMAIL", "admin@jurumatch.local").strip().lower()
        admin_password = os.getenv("ADMIN_PASSWORD", "admin12345")
        if admin_email and admin_password:
            from werkzeug.security import generate_password_hash
            existing = _execute(konn, "SELECT id FROM users WHERE email=%s", (admin_email,)).fetchone()
            if existing is None:
                _execute(
                    konn,
                    "INSERT INTO users (nama,email,password_hash,role,dibuat_pada) VALUES (%s,%s,%s,%s,%s)",
                    ("Administrator", admin_email, generate_password_hash(admin_password), "admin",
                     datetime.now().isoformat(timespec="seconds")),
                )

        konn.commit()
    finally:
        konn.close()


def create_user(nama, email, password_hash, role="user"):
    konn = get_koneksi()
    try:
        if USE_POSTGRES:
            cur = _execute(konn, """
                INSERT INTO users (nama,email,password_hash,role,dibuat_pada)
                VALUES (%s,%s,%s,%s,%s) RETURNING id
            """, (nama, email.lower(), password_hash, role, datetime.now().isoformat(timespec="seconds")))
            row = cur.fetchone()
            konn.commit()
            return row["id"] if row else None

        cur = _execute(konn, "INSERT INTO users (nama,email,password_hash,role,dibuat_pada) VALUES (%s,%s,%s,%s,%s)",
                       (nama, email.lower(), password_hash, role, datetime.now().isoformat(timespec="seconds")))
        konn.commit()
        return cur.lastrowid
    except Exception as exc:
        # Preserve the original behavior for duplicate emails without hiding
        # unrelated database errors.
        if "unique" in str(exc).lower() or "duplicate" in str(exc).lower():
            konn.rollback()
            return None
        konn.rollback()
        raise
    finally:
        konn.close()


def get_user_by_email(email, role=None):
    konn = get_koneksi()
    try:
        sql = "SELECT * FROM users WHERE email=%s"
        params = [email.lower()]
        if role:
            sql += " AND role=%s"
            params.append(role)
        row = _execute(konn, sql, tuple(params)).fetchone()
        return dict(row) if row else None
    finally:
        konn.close()


def get_user(uid):
    konn = get_koneksi()
    try:
        row = _execute(konn, "SELECT * FROM users WHERE id=%s", (uid,)).fetchone()
        return dict(row) if row else None
    finally:
        konn.close()


def count_users():
    konn = get_koneksi()
    try:
        return _execute(konn, "SELECT COUNT(*) FROM users WHERE role='user'").fetchone()[0]
    finally:
        konn.close()


def count_results():
    konn = get_koneksi()
    try:
        return _execute(konn, "SELECT COUNT(*) FROM hasil_tes").fetchone()[0]
    finally:
        konn.close()


def simpan_hasil(user_id, nama, skor_riasec, kode_holland, rekomendasi):
    konn = get_koneksi()
    try:
        payload = json.dumps(rekomendasi, ensure_ascii=False)
        if USE_POSTGRES:
            cur = _execute(konn, """
                INSERT INTO hasil_tes
                (user_id,nama,skor_r,skor_i,skor_a,skor_s,skor_e,skor_c,kode_holland,rekomendasi_json,dibuat_pada)
                VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s) RETURNING id
            """, (user_id, nama, skor_riasec["R"], skor_riasec["I"], skor_riasec["A"], skor_riasec["S"],
                   skor_riasec["E"], skor_riasec["C"], kode_holland, payload,
                   datetime.now().isoformat(timespec="seconds")))
            row = cur.fetchone()
            konn.commit()
            return row["id"]

        cur = _execute(konn, """
            INSERT INTO hasil_tes
            (user_id,nama,skor_r,skor_i,skor_a,skor_s,skor_e,skor_c,kode_holland,rekomendasi_json,dibuat_pada)
            VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
        """, (user_id, nama, skor_riasec["R"], skor_riasec["I"], skor_riasec["A"], skor_riasec["S"],
               skor_riasec["E"], skor_riasec["C"], kode_holland, payload,
               datetime.now().isoformat(timespec="seconds")))
        konn.commit()
        return cur.lastrowid
    finally:
        konn.close()


def ambil_hasil(i, user_id=None, admin=False):
    konn = get_koneksi()
    try:
        if admin:
            row = _execute(konn, "SELECT * FROM hasil_tes WHERE id=%s", (i,)).fetchone()
        else:
            row = _execute(konn, "SELECT * FROM hasil_tes WHERE id=%s AND user_id=%s", (i, user_id)).fetchone()
        if not row:
            return None
        d = dict(row)
        d["rekomendasi"] = json.loads(d["rekomendasi_json"])
        return d
    finally:
        konn.close()


def riwayat_user(uid):
    konn = get_koneksi()
    try:
        rows = _execute(konn, "SELECT id,nama,kode_holland,dibuat_pada FROM hasil_tes WHERE user_id=%s ORDER BY id DESC", (uid,)).fetchall()
        return [dict(r) for r in rows]
    finally:
        konn.close()


def semua_pengguna():
    konn = get_koneksi()
    try:
        rows = _execute(konn, "SELECT id,nama,email,role,dibuat_pada FROM users ORDER BY id DESC").fetchall()
        return [dict(r) for r in rows]
    finally:
        konn.close()


def semua_hasil():
    konn = get_koneksi()
    try:
        rows = _execute(konn, """SELECT h.id,h.nama,h.kode_holland,h.dibuat_pada,u.email
          FROM hasil_tes h LEFT JOIN users u ON u.id=h.user_id ORDER BY h.id DESC""").fetchall()
        return [dict(r) for r in rows]
    finally:
        konn.close()


def riwayat_semua():
    return semua_hasil()
